<?php
define('LAYERACC_ID', FALSE);
define('LAYERACC_INDEX', TRUE);

define('LAYERACC_LAYER', FALSE);
define('LAYERACC_ARRAY', TRUE);

define('LAYERACC_UNWRAP', TRUE);
define('LAYERACC_WRAP', FALSE);
