<?php


namespace App\Form;


use Cake\Event\EventManager;
use Cake\Form\Form;
use Cake\Form\Schema;
use Cake\ORM\TableRegistry;

class ArtworkFilter extends Form
{
    public function __construct(EventManager $eventManager = null)
    {
        parent::__construct($eventManager);
    }

    /**
     * A hook method intended to be implemented by subclasses.
     *
     * You can use this method to define the schema using
     * the methods on Cake\Form\Schema, or loads a pre-defined
     * schema from a concrete class.
     *
     * @param \Cake\Form\Schema $schema The schema to customize.
     * @return \Cake\Form\Schema The schema to use.
     */
    protected function _buildSchema(\Cake\Form\Schema $schema)
    {
        $schema
            ->addField('title_mode', ['type' => 'boolean'])
            ->addField('description_mode', ['type' => 'boolean']);
        $Table = TableRegistry::getTableLocator()->get('Artworks');
        $TableSchema = $Table->getSchema();

        foreach ($TableSchema->columns() as $name) {
            $schema->addField($name, $TableSchema->getColumn($name));
        }
        return $schema;
    }

    protected function _execute(array $data)
    {
        return parent::_execute($data); // TODO: Change the autogenerated stub
    }

    public function execute(array $data)
    {
        return parent::execute($data); // TODO: Change the autogenerated stub
    }

}
