<?php


namespace App\Form;


use Cake\Form\Form;
use Cake\Form\Schema;

class ArtworkFilter extends Form
{
    /**
     * A hook method intended to be implemented by subclasses.
     *
     * You can use this method to define the schema using
     * the methods on Cake\Form\Schema, or loads a pre-defined
     * schema from a concrete class.
     *
     * @param \Cake\Form\Schema $schema The schema to customize.
     * @return \Cake\Form\Schema The schema to use.
     */
    protected function _buildSchema(\Cake\Form\Schema $schema)
    {
        return $schema->addField('title', ['type' => 'string'])
            ->addField('title_mode', ['type' => 'boolean'])
            ->addField('description', ['type' => 'text'])
            ->addField('description_mode', ['type' => 'boolean'])
            ;
    }

    protected function _execute(array $data)
    {
        return parent::_execute($data); // TODO: Change the autogenerated stub
    }

    public function execute(array $data)
    {
        return parent::execute($data); // TODO: Change the autogenerated stub
    }

}
