<?php
namespace App\Controller\Component;


use App\Controller\AppController;
use App\Model\Entity\Preference;
use App\Model\Table\PreferencesTable;
use Cake\Controller\Component;
use Cake\ORM\TableRegistry;

/**
 * Class PreferencesComponent
 * @package App\Controller\Component
 *
 * @method Component getController() : AppController
 */
class PreferencesComponent extends Component
{

    /**
     * @var bool|PreferencesTable
     */
    private $repository = false;

    public function initialize(array $config)
    {
        parent::initialize($config); // TODO: Change the autogenerated stub
        $this->getController()->viewBuilder()->helpers(['Preferences']);
    }

    public function setPref()
    {
        $controller = $this->getController();
        /* @var AppController $controller */
        $supervisor_id = $controller->contextUser()->getId('supervisor');

        //New prefs arrive in some standard, decodable POST (or GET?)

        //read the persisted prefs
        $prefs = $this->repository()->getPreferncesFor($supervisor_id);
        /* @var Preference $prefs */

        osd($prefs->for($prefs::LIMIT), '$prefs->for($prefs::LIMIT)');
        osd($prefs->for($prefs::SHIPPING), '$prefs->for($prefs::SHIPPING');
        osd($prefs->for($prefs::SHIPPING_METHOD), '$prefs->for($prefs::SHIPPING_METHOD');
//        die;
        //Modify prefs to contain new setting
        //write the prefs to storage
//        return $controller->redirect($controller->referer());
    }

    /**
     * Get the Preferences table instance
     *
     * @return PreferencesTable
     */
    private function repository()
    {
        if ($this->repository === false) {
            $this->repository = TableRegistry::getTableLocator()->get('Preferences');
        }
        return $this->repository;
    }

}
