<?php
namespace App\Controller\Component;


use App\Controller\AppController;
use App\Model\Entity\Preference;
use App\Model\Table\PreferencesTable;
use Cake\Controller\Component;
use Cake\Core\App;
use Cake\ORM\TableRegistry;
use Cake\Utility\Hash;
use Cake\Utility\Text;

/**
 * Class PreferencesComponent
 * @package App\Controller\Component
 *
 * @method AppController getController()
 * @property \FlashComponent $Flash
 */
class PreferencesComponent extends Component
{

    /**
     * @var bool|PreferencesTable
     */
    private $repository = false;

    public $components = ['Flash'];

    public function initialize(array $config)
    {
        parent::initialize($config); // TODO: Change the autogenerated stub
        $this->getController()->viewBuilder()->helpers(['Preferences']);

    }

    public function setPref()
    {
        $controller = $this->getController();
        /* @var AppController $controller */

        if ($controller->getRequest()->is('post')) { //New prefs arrive in some standard, decodable POST (or GET?)
            $post = Hash::flatten($controller->getRequest()->getData());
            $supervisor_id = $controller->contextUser()->getId('supervisor');
            //read the persisted prefs
            $prefs = $this->repository()->getPreferencesFor($supervisor_id);
            /* @var Preference $prefs */
            $errors = [];

            osd($prefs);

            $settingSummaries = $this->summarizeSettings($posted ?? []);

            if (!$this->repository()->save($prefs)) {
                $msg = $settingSummaries->count >1
                    ? "Your preferences $settingSummaries->summaryStatement were not saved. Please try again"
                    : "Your preference for $settingSummaries->summaryStatement was not saved. Please try again";
                $this->Flash->error($msg);
            } else {
                $msg = $settingSummaries->count >1
                    ? "Your preferences $settingSummaries->summaryStatement were saved."
                    : "Your preference for $settingSummaries->summaryStatement was saved.";
                $this->Flash->error($msg);
            }

            if (count($errors) > 0) {
                foreach ($errors as $error) {
                    $this->Flash->error($error);
                }
            }

        } else {
            $msg = "Not a post";
            $this->Flash->error($msg);
        }
        return $controller->redirect($controller->referer());
}

    /**
     * Unset one user preference
     *
     * @param $path
     */
    public function clearPref($path)
    {
        $controller = $this->getController();
        /* @var AppController $controller */
        $supervisor_id = $controller->contextUser()->getId('supervisor');

        //read the persisted prefs
        $prefs = $this->repository()->getPreferncesFor($supervisor_id);
        /* @var Preference $prefs */

        $prefs->prefs = Hash::remove($prefs->prefs, $path);


    }

    /**
     * Make a simple object with versions of the posted user prefs for messaging
     *
     * $post is posted data array
     *  [
     *      ['path.to.set' => 'value']
     *      ['another.pref => '42']
     *  ]
     *
     * From that example $prefsSummary will be:
     * stdClass {
     *  post =              ['path.to.set' => 'value',
     *                       'another.pref' => '42']
     *  summaryArray =      ['path, to, set = value',
     *                       'another, pref = 42']
     *  summaryStatement =  'path, to, set = value and another, path = 42'
     *  count =             2
     * }
     *
     * @param array $post
     * @return \stdClass
     */
    private function summarizeSettings(array $post): \stdClass
    {
        $settings = collection($post);
        $settingSummaries = $settings->map(function ($value, $key) {
            $pref = str_replace('.', ', ', $key);
            return "[$pref = $value]";
        });

        $prefsSummary = new \stdClass();
        $prefsSummary->post = $post;
        $prefsSummary->summaryArray = $settingSummaries->toArray();
        $prefsSummary->summaryStatement = Text::toList($settingSummaries->toArray());
        $prefsSummary->count = count($post);

        return $prefsSummary;
    }

    /**
     * Get the Preferences table instance
     *
     * @return PreferencesTable
     */
    private function repository()
    {
        if ($this->repository === false) {
            $this->repository = TableRegistry::getTableLocator()->get('Preferences');
        }
        return $this->repository;
    }

}
